import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import path from "node:path"
import test from "node:test"

test("MarginNote 的 file 页面使用原生桥接而不是预览数据", () => {
  const source = readFileSync(path.join(process.cwd(), "web", "src", "lib", "mnBridge.js"), "utf8")
  assert.match(source, /__MN_FULL_UI_PREVIEW__/)
  assert.match(source, /mnaddon:\/\/bridge/)
  assert.doesNotMatch(source, /location\.protocol\s*===\s*["']file:/)
})

test("插件面板不再包含液态玻璃原生调用或透明联动", () => {
  const panel = readFileSync(path.join(process.cwd(), "rails-native", "WebPanelController.js"), "utf8")
  assert.doesNotMatch(panel, /UIGlassEffect|UIVisualEffectView|nativeLiquidGlass|nativeGlassMounted/)
})

test("跨脑图定位原题时只使用稳定会话尺寸，不采样切换过程中的临时 frame", () => {
  const addon = readFileSync(path.join(process.cwd(), "rails-native", "WebAddon.js"), "utf8")
  const panel = readFileSync(path.join(process.cwd(), "rails-native", "WebPanelController.js"), "utf8")
  assert.match(addon, /self\.pendingMistakeNavigation[\s\S]*preservePanelForNotebookSwitch/)
  assert.match(addon, /preserveAcrossNotebookSwitch[\s\S]*restorePanelAfterNotebookSwitch/)
  const preserve = panel.match(/function preservePanelForNotebookSwitch[\s\S]*?\n  \}/)?.[0] || ""
  assert.match(preserve, /controller\.view\.frame = savedFrame\(controller\)/)
  assert.doesNotMatch(preserve, /saveFrame\(controller\)|removeFromSuperview/)
  const restore = panel.match(/function restorePanelAfterNotebookSwitch[\s\S]*?\n  \}/)?.[0] || ""
  assert.match(restore, /var frame = savedFrame\(controller\)/)
  assert.doesNotMatch(restore, /__onPanelShow/)
  assert.match(panel, /controller\.view\.autoresizingMask = 0/)
  assert.match(panel, /function ensureLayout[\s\S]*controller\.view\.frame = savedFrame\(controller\)/)
  const close = panel.match(/function closePanel[\s\S]*?\n  \}/)?.[0] || ""
  assert.doesNotMatch(close, /saveFrame\(controller\)/)
})

test("插件根页面固定，仅内容页和专用面板滚动", () => {
  const css = readFileSync(path.join(process.cwd(), "web", "src", "ui-reference-final.css"), "utf8")
  assert.match(css, /\.shell > main\s*\{\s*overflow:\s*hidden !important/)
  assert.match(css, /\.overviewPage,[\s\S]*?\.exportPage\s*\{[\s\S]*?overflow:\s*auto/)
  assert.doesNotMatch(css, /\.shell > main\s*\{[^}]*overflow-y:\s*scroll/)
})

test("默认构建完全由开发源码生成，不再依赖 runtime baseline", () => {
  const pkg = JSON.parse(readFileSync(path.join(process.cwd(), "package.json"), "utf8"))
  const build = readFileSync(path.join(process.cwd(), "build.mjs"), "utf8")
  assert.equal(pkg.scripts.build, "node build.mjs")
  assert.equal(pkg.scripts["build:source"], "node build.mjs")
  assert.doesNotMatch(JSON.stringify(pkg.scripts), /legacy-runtime|build-runtime/)
  assert.match(build, /src["'],\s*["']rails-core\.ts/)
  assert.match(build, /web["'],\s*["']vite\.config\.js/)
})

test("错题详情 UI 由源码实现并保持批准预览的工具栏结构", () => {
  const source = readFileSync(path.join(process.cwd(), "web", "src", "main.jsx"), "utf8")
  const css = readFileSync(path.join(process.cwd(), "web", "src", "ui-reference-final.css"), "utf8")
  assert.match(source, /ui-reference-final\.css/)
  assert.match(source, /previewLevelSelect/)
  assert.match(source, /detailTagPicker/)
  assert.match(source, /detailRemoveMistake/)
  assert.match(source, /detailTabRightGroup detailTabAux/)
  assert.match(source, /onLoad=\{wirePreviewFrame\}/)
  assert.match(css, /@container detailPane \(max-width: 430px\)/)
  assert.match(css, /grid-template-columns: minmax\(0, 1fr\) minmax\(0, 1\.16fr\) 62px 74px/)
  assert.match(css, /preview-level-0[^}]*#d85f4b/)
  assert.match(css, /preview-level-5[^}]*#4f735e/)
})

test("2.3.2 详情交互修复进入源码构建", () => {
  const source = readFileSync(path.join(process.cwd(), "web", "src", "main.jsx"), "utf8")
  const css = readFileSync(path.join(process.cwd(), "web", "src", "ui-reference-final.css"), "utf8")
  const icons = readFileSync(path.join(process.cwd(), "web", "src", "icons.jsx"), "utf8")
  const core = readFileSync(path.join(process.cwd(), "src", "rails-core.ts"), "utf8")
  const manager = readFileSync(path.join(process.cwd(), "src", "mistake-manager.ts"), "utf8")
  const cardHtml = readFileSync(path.join(process.cwd(), "src", "card-html.ts"), "utf8")
  const build = readFileSync(path.join(process.cwd(), "build.mjs"), "utf8")

  assert.match(source, /__mnPinchZoomBound/)
  assert.match(source, /gesturechange/)
  assert.match(source, /touchmove/)
  assert.match(source, /card\.style\.transform = `scale\(\$\{scale\}\)`/)
  assert.match(source, /card\.style\.width = `\$\{baseWidth\}px`/)
  assert.doesNotMatch(source, /documentElement\.style\.zoom/)
  assert.match(cardHtml, /maximum-scale=1,user-scalable=no/)
  assert.match(source, /目前没有到期错题[^\n]*icon=\{false\}/)
  assert.match(source, /previewLevelSelect[^\n]*\{index\}级<\/option>/)
  assert.match(source, /detailTagDelete/)
  assert.match(source, /tagDeleteConfirmOverlay/)
  assert.match(source, /deleteMistakeTag/)
  assert.match(icons, /trash:/)
  assert.match(core, /command === "deleteMistakeTag"/)
  assert.match(manager, /export async function deleteMistakeTag/)
  assert.match(build, /webDist, "logo\.png"/)
  assert.doesNotMatch(source, /src="\.\/logo\.png"/)
  assert.match(source, /MindMapMultiSelect/)
  assert.match(source, /buildParentInsights/)
  assert.match(source, /mindMapSelectTrigger/)
  assert.match(css, /\.mindMapSelect/)
  assert.match(source, /<MistakeDetail key=\{detail\.record\.recordId\}/)
  assert.match(source, /key=\{`\$\{detail\.record\.recordId\}:question`\}/)
  assert.match(source, /key=\{`\$\{detail\.record\.recordId\}:answer:/)
  assert.match(css, /\.listToolbar > \.batchToggle/)
  assert.match(css, /text-overflow: ellipsis !important/)
})

test("运行日志只在独立调试功能区显示并通过原生桥接保存文本", () => {
  const source = readFileSync(path.join(process.cwd(), "web", "src", "main.jsx"), "utf8")
  const core = readFileSync(path.join(process.cwd(), "src", "rails-core.ts"), "utf8")
  const navigation = readFileSync(path.join(process.cwd(), "src", "note-navigation.ts"), "utf8")
  const versionIndex = source.indexOf('"当前版本"')
  const logIndex = source.indexOf('"导出运行日志"')
  const debugGroupIndex = source.indexOf('title="调试功能"')
  assert.ok(versionIndex >= 0 && debugGroupIndex > versionIndex && logIndex > debugGroupIndex)
  assert.match(source, /taps\.count >= 5/)
  assert.match(source, /action\("setDebugMode", \{ enabled: true \}\)/)
  assert.match(source, /action\("exportRuntimeLog"/)
  assert.match(core, /command === "exportRuntimeLog"/)
  assert.match(navigation, /export function exportNavigationRuntimeLog/)
  assert.match(navigation, /writeTextFile\(path/)
  assert.match(navigation, /saveFile\(path, "public\.plain-text"\)/)
  assert.match(navigation, /if \(!loadMatcherSettings\(\)\.debugModeEnabled\) return/)
})

test("设置页可切换插件窗口关闭按钮位置", () => {
  const source = readFileSync(path.join(process.cwd(), "web", "src", "main.jsx"), "utf8")
  const bridge = readFileSync(path.join(process.cwd(), "rails-native", "WebBridgeCommands.js"), "utf8")
  const panel = readFileSync(path.join(process.cwd(), "rails-native", "WebPanelController.js"), "utf8")
  assert.match(source, /"插件窗口关闭按钮"/)
  assert.match(source, /action\("setPanelCloseButtonSide"/)
  assert.match(bridge, /command === "setPanelCloseButtonSide"/)
  assert.match(panel, /function setCloseButtonSide/)
  assert.match(source, /action\("closePanel", null, false\)/)
  assert.match(source, /<Icon name="close" \/>/)
  assert.ok(source.includes('panelCloseSide === "left" && <>{closeButton}{refreshButton}</>'))
  assert.ok(source.includes('panelCloseSide === "right" && <>{refreshButton}{closeButton}</>'))
  assert.doesNotMatch(panel, /UIButton\.buttonWithType|controller\.closeButton/)
  assert.match(panel, /beta\.rails\.close-side\.v1/)
})

test("插件网页延伸到原生关闭按钮行且设置项位于插件分组", () => {
  const source = readFileSync(path.join(process.cwd(), "web", "src", "main.jsx"), "utf8")
  const css = readFileSync(path.join(process.cwd(), "web", "src", "beta-ui.css"), "utf8")
  const panel = readFileSync(path.join(process.cwd(), "rails-native", "WebPanelController.js"), "utf8")
  const answerGroupEnd = source.indexOf(']} />', source.indexOf('<SettingsGroup title="答案匹配"'))
  const pluginGroupStart = source.indexOf('<SettingsGroup title="插件"')
  const settingIndex = source.indexOf('"插件窗口关闭按钮"')
  assert.ok(settingIndex > pluginGroupStart && settingIndex > answerGroupEnd)
  assert.match(source, /className=\{trailing \? "hasTrailing" : ""\}/)
  assert.match(css, /button\.hasTrailing::after \{ content: none; \}/)
  assert.match(css, /\.topTools-left \{ grid-column: 1/)
  assert.match(css, /\.topTools-right \{ grid-column: 3/)
  assert.match(panel, /y: 0,[\s\S]*height: frame\.height/)
  assert.match(panel, /controller\.view\.addSubview\(controller\.webView\)/)
  assert.doesNotMatch(panel, /controller\.view\.addSubview\(controller\.titleBar\)/)
})

test("整条顶栏除按钮组外可拖动、Tab 居中且顶栏为白色", () => {
  const source = readFileSync(path.join(process.cwd(), "web", "src", "main.jsx"), "utf8")
  const css = readFileSync(path.join(process.cwd(), "web", "src", "beta-ui.css"), "utf8")
  const panel = readFileSync(path.join(process.cwd(), "rails-native", "WebPanelController.js"), "utf8")
  assert.match(panel, /controller\.headerPan = new UIPanGestureRecognizer\(controller, "handleHeaderPan:"\)/)
  assert.match(panel, /controller\.headerPan\.cancelsTouchesInView = false/)
  assert.match(panel, /controller\.headerPan\.delegate = controller/)
  assert.match(panel, /gestureRecognizerShouldBegin/)
  assert.match(panel, /insideHeader && !insideControls/)
  assert.match(panel, /Number\(start\.y\) <= TITLE_HEIGHT/)
  assert.doesNotMatch(panel, /leftDragArea|rightDragArea|titleDragArea/)
  assert.match(panel, /CONTROL_CLUSTER_WIDTH/)
  assert.match(panel, /controller\.webView\.opaque = false/)
  assert.match(panel, /controller\.webView\.layer\.cornerRadius = 14/)
  assert.match(source, /const refreshButton = <button className="iconButton"/)
  assert.match(source, /const closeButton = <button className="iconButton"/)
  assert.match(css, /\.topBar \{[\s\S]*background: #fff !important/)
  assert.match(css, /-webkit-backdrop-filter: none/)
  assert.doesNotMatch(css, /\.shell::after/)
  assert.match(css, /\.shell > main \{[\s\S]*height: 100% !important;[\s\S]*margin: 0 !important;[\s\S]*border-radius: 14px/)
  assert.match(css, /html, body, #root \{ background: transparent !important; \}/)
  assert.match(css, /grid-template-columns: minmax\(90px, 1fr\) auto minmax\(90px, 1fr\) !important/)
  assert.match(source, /topTools topTools-left[\s\S]*panelCloseSide === "left"[\s\S]*<nav className="topNav">[\s\S]*topTools topTools-right[\s\S]*panelCloseSide === "right"/)
  assert.doesNotMatch(source, /className="appBrand"/)
})

test("左侧按钮始终贴边且错题候选显示全部自定义标签", () => {
  const source = readFileSync(path.join(process.cwd(), "web", "src", "main.jsx"), "utf8")
  const css = readFileSync(path.join(process.cwd(), "web", "src", "beta-ui.css"), "utf8")
  const preview = readFileSync(path.join(process.cwd(), "web", "src", "lib", "previewBridge.js"), "utf8")
  assert.match(css, /\.topTools \{[^}]*margin-left: 0 !important;[^}]*margin-right: 0 !important;/)
  assert.match(css, /\.topTools-left \{[^}]*justify-self: start !important;/)
  assert.match(source, /Array\.isArray\(item\.manualCategories\)/)
  assert.match(source, /item\.manualCategory \? \[item\.manualCategory\] : \[\]/)
  assert.match(source, /className="mistakeItemTags"/)
  assert.match(source, /manualTags\.map\(tag => <em key=\{tag\}>#\{tag\}<\/em>\)/)
  assert.match(source, /manualTags\.length > 0 \? <span className="mistakeItemTags">[\s\S]*: <small>\{item\.categoryLabel\}<\/small>/)
  assert.match(css, /\.mistakeItemTags > em/)
  assert.match(preview, /manualCategories: \["概念辨析", "需要重做"\]/)
})

test("实验性 UI 使用 MN Liquid Glass Demo 顶栏并保留关闭后白色顶栏", () => {
  const source = readFileSync(path.join(process.cwd(), "web", "src", "main.jsx"), "utf8")
  const css = readFileSync(path.join(process.cwd(), "web", "src", "liquid-glass-topbar.css"), "utf8")
  const runtime = readFileSync(path.join(process.cwd(), "web", "src", "liquid-glass-topbar.js"), "utf8")
  const baseCss = readFileSync(path.join(process.cwd(), "web", "src", "beta-ui.css"), "utf8")
  assert.match(source, /experimentalGlassEnabled \? "mn-liquid-glass-topbar"/)
  assert.match(source, /mountLiquidGlassTopbar\(\)/)
  assert.match(source, /unmountLiquidGlassTopbar\(\)/)
  assert.match(css, /\.mn-liquid-glass-topbar \.topBar \{[\s\S]*border-radius: 25px/)
  assert.match(css, /\.mn-liquid-glass-topbar \.topNav::before/)
  assert.match(runtime, /function setLensGeometry/)
  assert.match(runtime, /function snapToButton/)
  assert.match(runtime, /--lg-predict-ms/)
  assert.match(baseCss, /\.topBar \{[\s\S]*background: #fff !important/)
})

test("实验模式让页面穿过悬浮顶栏并使用滚动同步的玻璃取样", () => {
  const optics = readFileSync(path.join(process.cwd(), "web", "src", "liquid-glass-topbar-optics.js"), "utf8")
  const glass = readFileSync(path.join(process.cwd(), "web", "src", "just-glass-debug.js"), "utf8")
  const settings = readFileSync(path.join(process.cwd(), "web", "src", "glass-optics-settings.js"), "utf8")
  const css = readFileSync(path.join(process.cwd(), "web", "src", "liquid-glass-topbar.css"), "utf8")
  assert.match(optics, /backgroundCanvas\.id="mnJustGlassBackground"/)
  assert.match(optics, /opticalCanvas\.id="mnLiquidTopbarOptics"/)
  assert.match(optics, /float transmitted=asin/)
  assert.match(optics, /RGB DISPERSION/)
  assert.match(optics, /html2canvas\(page/)
  assert.match(optics, /page\.getBoundingClientRect\(\)/)
  assert.match(optics, /sceneContext\.drawImage\(pageSnapshot\.canvas/)
  assert.match(optics, /gl\.texSubImage2D/)
  assert.match(optics, /export function getLiquidGlassComposedScene/)
  assert.match(optics, /document\.body\.appendChild\(opticalCanvas\)/)
  assert.match(optics, /captureFrame\(frame, scale\)/)
  assert.match(optics, /frameSnapshots\.forEach/)
  assert.match(optics, /frame\.contentWindow/)
  assert.match(css, /\.mn-liquid-optical-ready \.mn-liquid-glass-topbar \.topBar/)
  assert.match(css, /#mnLiquidTopbarOptics \{[^}]*z-index: 89/)
  assert.match(css, /\.mn-liquid-glass-topbar\.shell > main \{[\s\S]*overflow-y: auto !important/)
  assert.match(css, /\.mn-liquid-glass-topbar \.settingsPage,[\s\S]*overflow: visible !important/)
  assert.match(css, /\.mn-liquid-glass-topbar \.topBar \{[\s\S]*position: sticky !important/)
  const scheduler = glass.match(/function scheduleCapture\(immediate\)[\s\S]*?\n\}/)?.[0] || ""
  assert.match(scheduler, /if \(captureRunning \|\| captureTimer\) return/)
  assert.match(scheduler, /Math\.max\(0, 48 - elapsed\)/)
  assert.doesNotMatch(scheduler, /clearTimeout/)
  assert.match(glass, /if \(captureQueued\) scheduleCapture\(true\)/)
  assert.match(glass, /function scrollSignature\(\)/)
  assert.match(glass, /if \(nextScrollSignature !== lastScrollSignature\)/)
  assert.match(glass, /getLiquidGlassComposedScene\(\)/)
  assert.match(glass, /id="mnGlassControls"/)
  assert.match(glass, /data-glass-optic/)
  assert.match(glass, /setLiquidGlassCustomBackground/)
  assert.match(settings, /balanced:[\s\S]*control:[\s\S]*frosted:[\s\S]*lens:/)
  assert.match(glass, /gl\.texSubImage2D/)
  assert.doesNotMatch(glass, /addEventListener\("scroll", scheduleCapture/)
  assert.doesNotMatch(glass, /observer\.observe\(appRoot, \{[^}]*attributes: true/)
})
